'use strict';
import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__proxy__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,filter,float,
getattr,hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip} from"./org.transcrypt.__runtime__.js";var __name__="__main__";export var HEADER_LENGTH=10;export var IP="127.0.0.1";export var PORT=1234;export var my_username=input("Username: ");export var client_socket=socket.socket(socket.AF_INET,socket.SOCK_STREAM);client_socket.connect(tuple([IP,
PORT]));client_socket.setblocking(false);export var username=my_username.encode("utf-8");export var username_header="{}".format(len(username)).encode("utf-8");client_socket.send(username_header+username);while(true){var message=input("{}{}".format(my_username));if(message){var message=message.encode("utf-8");var message_header="{}".format(len(message)).encode("utf-8");client_socket.send(message_header+message)}try{while(true){var username_header=client_socket.recv(HEADER_LENGTH);if(!len(username_header)){print("Connection closed by the server");
sys.exit()}var username_length=int(username_header.decode("utf-8").strip());var username=client_socket.recv(username_length).decode("utf-8");var message_header=client_socket.recv(HEADER_LENGTH);var message_length=int(message_header.decode("utf-8").strip());var message=client_socket.recv(message_length).decode("utf-8");print("{}{}{}".format(username,message))}}catch(__except0__){if(isinstance(__except0__,IOError)){var e=__except0__;if(e.errno!=errno.EAGAIN&&e.errno!=errno.EWOULDBLOCK){print("Reading error: {}".format(str(e)));
sys.exit()}continue}else if(isinstance(__except0__,Exception)){var e=__except0__;print("Reading error: ".format(str(e)));sys.exit()}else throw __except0__;}};

//# sourceMappingURL=client.map
